spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/attendance-system-central
      username: postgres
      password: postgres
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always

  #  flyway:
  #    baseline-on-migrate: true
  #    clean-on-validation-error: true


  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  redis:
    database: 0
    host: localhost
    port: 6379
  jackson:
    time-zone: IST
    default-property-inclusion: NON_NULL

  #    serialization:
  #      WRITE_DATES_AS_TIMESTAMPS: false

  #  logging.level: INFO

  jwt:
    secret: JWTSuperSecretKey
    expirationTimeMs: 604800000

server:
  port: 8080

logging:
  level:
    org.jooq: ERROR
    org.hibernate.SQL: ERROR
    attendance.system.central.controller: INFO
    attendance.system.central.dao: INFO
    attendance.system.central.service: INFO

#management:
#  Endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include:

#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
